# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Basys3_XDC/MY_Basys-3-Master.xdc

# Block Designs: bd/design_MicroBlaze_Fnd/design_MicroBlaze_Fnd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicroBlaze_Fnd || ORIG_REF_NAME==design_MicroBlaze_Fnd} -quiet] -quiet

# IP: bd/design_MicroBlaze_Fnd/ip/design_MicroBlaze_Fnd_microblaze_0_0/design_MicroBlaze_Fnd_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicroBlaze_Fnd_microblaze_0_0 || ORIG_REF_NAME==design_MicroBlaze_Fnd_microblaze_0_0} -quiet] -quiet

# IP: bd/design_MicroBlaze_Fnd/ip/design_MicroBlaze_Fnd_axi_uartlite_0_0/design_MicroBlaze_Fnd_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicroBlaze_Fnd_axi_uartlite_0_0 || ORIG_REF_NAME==design_MicroBlaze_Fnd_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_MicroBlaze_Fnd/ip/design_MicroBlaze_Fnd_axi_gpio_0_0/design_MicroBlaze_Fnd_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicroBlaze_Fnd_axi_gpio_0_0 || ORIG_REF_NAME==design_MicroBlaze_Fnd_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_MicroBlaze_Fnd/ip/design_MicroBlaze_Fnd_axi_gpio_1_0/design_MicroBlaze_Fnd_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicroBlaze_Fnd_axi_gpio_1_0 || ORIG_REF_NAME==design_MicroBlaze_Fnd_axi_gpio_1_0} -quiet] -quiet

# IP: bd/design_MicroBlaze_Fnd/ip/design_MicroBlaze_Fnd_AXI4_TICK_0_0/design_MicroBlaze_Fnd_AXI4_TICK_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicroBlaze_Fnd_AXI4_TICK_0_0 || ORIG_REF_NAME==design_MicroBlaze_Fnd_AXI4_TICK_0_0} -quiet] -quiet

# IP: bd/design_MicroBlaze_Fnd/ip/design_MicroBlaze_Fnd_AXI4_FND_0_0/design_MicroBlaze_Fnd_AXI4_FND_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicroBlaze_Fnd_AXI4_FND_0_0 || ORIG_REF_NAME==design_MicroBlaze_Fnd_AXI4_FND_0_0} -quiet] -quiet

# IP: bd/design_MicroBlaze_Fnd/ip/design_MicroBlaze_Fnd_dlmb_v10_0/design_MicroBlaze_Fnd_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicroBlaze_Fnd_dlmb_v10_0 || ORIG_REF_NAME==design_MicroBlaze_Fnd_dlmb_v10_0} -quiet] -quiet

# IP: bd/design_MicroBlaze_Fnd/ip/design_MicroBlaze_Fnd_ilmb_v10_0/design_MicroBlaze_Fnd_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicroBlaze_Fnd_ilmb_v10_0 || ORIG_REF_NAME==design_MicroBlaze_Fnd_ilmb_v10_0} -quiet] -quiet

# IP: bd/design_MicroBlaze_Fnd/ip/design_MicroBlaze_Fnd_dlmb_bram_if_cntlr_0/design_MicroBlaze_Fnd_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicroBlaze_Fnd_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_MicroBlaze_Fnd_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_MicroBlaze_Fnd/ip/design_MicroBlaze_Fnd_ilmb_bram_if_cntlr_0/design_MicroBlaze_Fnd_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicroBlaze_Fnd_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_MicroBlaze_Fnd_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_MicroBlaze_Fnd/ip/design_MicroBlaze_Fnd_lmb_bram_0/design_MicroBlaze_Fnd_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicroBlaze_Fnd_lmb_bram_0 || ORIG_REF_NAME==design_MicroBlaze_Fnd_lmb_bram_0} -quiet] -quiet

# IP: bd/design_MicroBlaze_Fnd/ip/design_MicroBlaze_Fnd_mdm_1_0/design_MicroBlaze_Fnd_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicroBlaze_Fnd_mdm_1_0 || ORIG_REF_NAME==design_MicroBlaze_Fnd_mdm_1_0} -quiet] -quiet

# IP: bd/design_MicroBlaze_Fnd/ip/design_MicroBlaze_Fnd_clk_wiz_1_0/design_MicroBlaze_Fnd_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicroBlaze_Fnd_clk_wiz_1_0 || ORIG_REF_NAME==design_MicroBlaze_Fnd_clk_wiz_1_0} -quiet] -quiet

# IP: bd/design_MicroBlaze_Fnd/ip/design_MicroBlaze_Fnd_rst_clk_wiz_1_100M_0/design_MicroBlaze_Fnd_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicroBlaze_Fnd_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_MicroBlaze_Fnd_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/design_MicroBlaze_Fnd/ip/design_MicroBlaze_Fnd_xbar_0/design_MicroBlaze_Fnd_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicroBlaze_Fnd_xbar_0 || ORIG_REF_NAME==design_MicroBlaze_Fnd_xbar_0} -quiet] -quiet

# IP: bd/design_MicroBlaze_Fnd/ip/design_MicroBlaze_Fnd_microblaze_0_axi_periph_0/design_MicroBlaze_Fnd_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicroBlaze_Fnd_microblaze_0_axi_periph_0 || ORIG_REF_NAME==design_MicroBlaze_Fnd_microblaze_0_axi_periph_0} -quiet] -quiet

# XDC: bd/design_MicroBlaze_Fnd/design_MicroBlaze_Fnd_ooc.xdc
